[build-system]
requires = ["setuptools>=42", "wheel", "cmake>=3.22", "pybind11-stubgen", "pyarrow>=10.0.0,<11"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = ["-ra", "--showlocals", "--strict-markers", "--strict-config"]
xfail_strict = true
filterwarnings = ["error"]
testpaths = ["python/tests"]


[tool.cibuildwheel]
build-verbosity = 0
before-all = [
    "yum install -y bzip2-devel libffi-devel zlib-devel wget python3-devel perl-IPC-Cmd perl-Test-Simple",
    "cd /usr/src && wget https://www.openssl.org/source/openssl-3.1.0.tar.gz",
    "tar -zxf openssl-3.1.0.tar.gz && rm openssl-3.1.0.tar.gz && cd /usr/src/openssl-3.1.0",
    "./config && make -j16 && make install",
    "ln -s /usr/local/lib64/libssl.so.3 /usr/lib64/libssl.so.3",
    "ln -s /usr/local/lib64/libcrypto.so.3 /usr/lib64/libcrypto.so.3"
]

environment = "CMAKE_ARGS_F=/tmp/cmake_args"
before-build = [
    "rm -rf {project}/CMakeCache.txt {project}/build {project}/CMakeFiles.txt {project}/_deps",
    "pip install pyarrow==10.0.0",
    "export PYST=$(python -c 'import site; print(site.getsitepackages()[0])')",
    "echo \"-DCMAKE_BUILD_TYPE=Release -DPYARROW_DIR=${PYST}/pyarrow/\" > ${CMAKE_ARGS_F}",
    "mkdir -p build/ukv",
]

skip = ["*musllinux*", "*i686*", "pp*", "cp36-*", "cp37-*", "cp38-*"]

archs = ["x86_64", "aarch64"]
repair-wheel-command = "auditwheel repair --lib-sdir . -w {dest_dir} {wheel}"
