name: Build_and_test

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches: ["main-dev"]
  pull_request:
    branches: ["main-dev"]


jobs:
  build:
    runs-on: 
      - label-1
      - self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Install ubuntu packages
        run: |
          echo "Unum runner"
          whoami
