name: Python_Java_Go

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]


jobs:
  build_and_test:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Install python packages
        run: |
          sudo apt update && \
          sudo apt install cmake python3-pip libssl-dev -y && \
          curl -fsSL https://get.docker.com -o get-docker.sh && \
          sudo sh get-docker.sh && \
          sudo usermod -aG docker runner && newgrp docker && \
          pip install cibuildwheel twine && export PATH=$PATH:~/.local/bin
          
      - name: Build and Test Python
        run: |
          CIBW_BUILD="cp39-*" cibuildwheel --platform linux && \
          CIBW_BUILD="cp310-*" cibuildwheel --platform linux

      - name: Build and Test Java
        run: |
          export JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64" && \
          bash java/pack.sh
          
      - name: Build GoLang
        run: |
          git submodule update --init --recursive --remote go-ukv/ && \
          bash go-ukv/pack.sh
