name: Python_Java_Go

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches: ["main-dev"]
  pull_request:
    branches: ["main-dev"]


jobs:
  build:
    runs-on: 
      - label-3
      - self-hosted
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Install python packages
        run: |
          pip install cibuildwheel twine && export PATH=$PATH:~/.local/bin
          
      - name: Build and Test Python
        run: |
          whoami
          docker ps -a
          CIBW_BUILD="cp39-*" cibuildwheel --platform linux && \
          CIBW_BUILD="cp310-*" cibuildwheel --platform linux

      - name: Build and Test Java
        run: |
          export JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64" && \
          bash java/pack.sh
          
      - name: Build GoLang
        run: |
          git submodule update --init --recursive --remote go-ukv/ && \
          bash go-ukv/pack.sh
